name: Run Aave V4 Spec

on:
  repository_dispatch:
    types: [on-demand-test]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

concurrency:
  group: ${{ github.workflow }}-tests-on-demand
  cancel-in-progress: true

jobs:   
  run-tests:
    name: All Tests
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || github.event.client_payload.environment || 'staging' }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      ETHEREUM_TENDERLY_FORK_ID: ${{ vars.ETHEREUM_TENDERLY_FORK_ID }}
      ETHEREUM_TENDERLY_PUBLIC_RPC: ${{ vars.ETHEREUM_TENDERLY_PUBLIC_RPC }}
      ETHEREUM_TENDERLY_ADMIN_RPC: ${{ secrets.ETHEREUM_TENDERLY_ADMIN_RPC }}
      ETHEREUM_TENDERLY_BLOCKEXPLORER: ${{ vars.ETHEREUM_TENDERLY_BLOCKEXPLORER }}
      API_X_E2E_TESTS_HEADER: ${{ secrets.API_X_E2E_TESTS_HEADER }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm build

      - name: Run tests
        run: pnpm spec
      
      - name: Publish results
        if: always()
        run: pnpm publish:results
