permissions:
  id-token: write
  contents: read
  packages: write

name: Pre-release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    env:
      ETHEREUM_TENDERLY_FORK_ID: ${{ vars.ETHEREUM_TENDERLY_FORK_ID }}
      ETHEREUM_TENDERLY_PUBLIC_RPC: ${{ vars.ETHEREUM_TENDERLY_PUBLIC_RPC }}
      ETHEREUM_TENDERLY_BLOCKEXPLORER: ${{ vars.ETHEREUM_TENDERLY_BLOCKEXPLORER }}
    needs: verify
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Create Snapshot
        id: create_snapshot
        run: pnpm changeset version --snapshot canary || echo "No unreleased changesets found"

      - name: Check for Changeset
        id: check_changeset
        run: echo "changeset_exists=$(grep -q 'No unreleased changesets found' <<< '${{ steps.create_snapshot.outputs.stdout }}' && echo false || echo true)" >> $GITHUB_ENV

      - name: Build
        if: env.changeset_exists == 'true'
        run: pnpm build

      - name: Publish Snapshot
        if: env.changeset_exists == 'true'
        run: pnpm changeset publish --snapshot --tag latest --no-git-tag
        env:
          NPM_CONFIG_PROVENANCE: false #PROVENANCE IS NOT SUPPORTED FOR SNAPSHOT PUBLISHES
