name: 'Verify'
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.5

      - name: Run Biome
        run: biome ci .

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      ENVIRONMENT: staging
      PRIVY_TEST_APP_ID: ${{ vars.PRIVY_TEST_APP_ID }}
      PRIVY_TEST_APP_SECRET: ${{ secrets.PRIVY_TEST_APP_SECRET }}
      PRIVY_TEST_WALLET_ID: ${{ vars.PRIVY_TEST_WALLET_ID }}
      PRIVY_TEST_WALLET_ADDRESS: ${{ vars.PRIVY_TEST_WALLET_ADDRESS }}
      ETHEREUM_TENDERLY_FORK_ID: ${{ vars.ETHEREUM_TENDERLY_FORK_ID }}
      ETHEREUM_TENDERLY_PUBLIC_RPC: ${{ vars.ETHEREUM_TENDERLY_PUBLIC_RPC }}
      ETHEREUM_TENDERLY_ADMIN_RPC: ${{ secrets.ETHEREUM_TENDERLY_ADMIN_RPC }}
      ETHEREUM_TENDERLY_BLOCKEXPLORER: ${{ vars.ETHEREUM_TENDERLY_BLOCKEXPLORER }}
      THIRDWEB_TEST_SECRET_KEY: ${{ secrets.THIRDWEB_TEST_SECRET_KEY }}
      THIRDWEB_TEST_WALLET_ADDRESS: ${{ vars.THIRDWEB_TEST_WALLET_ADDRESS }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Lint
        shell: bash
        run: pnpm lint

      - name: GraphQL Check
        shell: bash
        run: pnpm check:graphql

      - name: Build
        shell: bash
        run: pnpm build

      - name: Run Tests
        shell: bash
        run: pnpm test
